// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {config} from '../models';
import {main} from '../models';

export function AddAllowlistDomain(arg1:string):Promise<void>;

export function AddCustomDomain(arg1:string):Promise<void>;

export function ConfirmCancel():Promise<void>;

export function EmergencyRestore():Promise<void>;

export function GetCatalog():Promise<Array<catalog.Group>>;

export function GetSettings():Promise<config.Settings>;

export function GetState():Promise<main.State>;

export function OpenDataDir():Promise<void>;

export function RemoveAllowlistDomain(arg1:string):Promise<void>;

export function RemoveCustomDomain(arg1:string):Promise<void>;

export function RequestCancel():Promise<main.CancelInfo>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWidget(arg1:boolean):Promise<void>;

export function SetWidgetOnTop(arg1:boolean):Promise<void>;

export function SetWidgetShape(arg1:string):Promise<void>;

export function StartSession(arg1:main.StartOptions):Promise<void>;

export function TestDomain(arg1:string):Promise<boolean>;
