// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowlistDomain(arg1) {
  return window['go']['main']['App']['AddAllowlistDomain'](arg1);
}

export function AddCustomDomain(arg1) {
  return window['go']['main']['App']['AddCustomDomain'](arg1);
}

export function ConfirmCancel() {
  return window['go']['main']['App']['ConfirmCancel']();
}

export function EmergencyRestore() {
  return window['go']['main']['App']['EmergencyRestore']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function RemoveAllowlistDomain(arg1) {
  return window['go']['main']['App']['RemoveAllowlistDomain'](arg1);
}

export function RemoveCustomDomain(arg1) {
  return window['go']['main']['App']['RemoveCustomDomain'](arg1);
}

export function RequestCancel() {
  return window['go']['main']['App']['RequestCancel']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWidget(arg1) {
  return window['go']['main']['App']['SetWidget'](arg1);
}

export function SetWidgetOnTop(arg1) {
  return window['go']['main']['App']['SetWidgetOnTop'](arg1);
}

export function SetWidgetShape(arg1) {
  return window['go']['main']['App']['SetWidgetShape'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function TestDomain(arg1) {
  return window['go']['main']['App']['TestDomain'](arg1);
}
